### ISSUE TITLE
Running Issue

### ISSUE THREAD

**Issue by richforest0506** [qlawmarq/fastapi-mysql-docker#43]
Hi, I am interested in this project.

But there is some questions.

1. How can I check existing and create table when api start.
I can't see any execution from mysql/db/00_user_table.sql

2. I need fetch data from third party api.
but I can't import requests.
```
...
import requests
...
```
In terminal
```
fast_api | Process SpawnProcess-49:
fast_api | Traceback (most recent call last):
fast_api |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
fast_api |     self.run()
fast_api |   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
fast_api |     self._target(*self._args, **self._kwargs)
fast_api |   File "/usr/local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
fast_api |     target(sockets=sockets)
fast_api |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 59, in run
fast_api |     return asyncio.run(self.serve(sockets=sockets))
fast_api |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
fast_api |     return loop.run_until_complete(main)
fast_api |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
fast_api |     return future.result()
fast_api |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 66, in serve
fast_api |     config.load()
fast_api |   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 471, in load
fast_api |     self.loaded_app = import_from_string(self.app)
fast_api |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
fast_api |     raise exc from None
fast_api |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
fast_api |     module = importlib.import_module(module_str)
fast_api |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
fast_api |     return _bootstrap._gcd_import(name[level:], package, level)
fast_api |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
fast_api |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
fast_api |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
fast_api |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
fast_api |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
fast_api |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
fast_api |   File "/app/main.py", line 4, in <module>
fast_api |     import requests
fast_api | ModuleNotFoundError: No module named 'requests'
```

If it is possible, please kindly answer.
Thanks and regards.

**Comment by qlawmarq** [comment]
@richforest0506 
Hi, thanks for your feedback.
You are using Docker, right?
If so, the `requests` lib is not pre-installed, as you can see in the `requirements.txt`.
- https://github.com/qlawmarq/fastapi-mysql-docker/blob/main/api/requirements.txt

`requests` must be added to requirements.txt as follows:

```txt
requests==2.30.0
```

Then try a re-build and see.

```bash
docker-compose build
```

**Comment by qlawmarq** [comment]
Sorry for the delay in answering your MySQL question.
The current code seems to cause an error in starting up the MySQL container, but I have fixed it.
You will see the following log when launching the MySQL container, so you can confirm that the query was executed with that.

```log
mysql     | 2023-05-17 00:28:48+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/00_user_table.sql
```

You can also check the table by actually executing a query using the following command.

```bash
docker-compose exec mysql bash
mysql -u root -p
mysql> USE fastapi_app;
mysql> SHOW TABLES;
```

**Comment by richforest0506** [comment]
Thanks for your kindly answers.
But when run "docker-compose up", docker doesn't create predefined tables in mysql/db.
When I check in mysql bash, the database is empty. I have to run it manually.
I'm sorry but let's ask one more time.

**Comment by qlawmarq** [comment]
@richforest0506 
Perhaps there is a volume that was created when the Docker was last started, so MySQL is reading the existing data (but empty) without initializing it.

Please try the following:

```bash
docker-compose down -v
docker-compose build
docker-compose up
```

Ref: https://docs.docker.com.zh.xy2401.com/v17.09/compose/reference/down/

Also, It would be effective to drop the instance once from the Docker management console, delete the volume, and then restart it.

**Comment by richforest0506** [comment]
yeah. running now.
Thank you very much.
